# Generated by Django 3.0.3 on 2020-03-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='agenda_completa',
            field=models.BooleanField(default=False, verbose_name='Agenda Completa'),
        ),
    ]
