# Generated by Django 3.0.3 on 2020-03-09 00:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_agenda_completa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='horarios',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), help_text='Adicione as horas separadas por vírgula, ex: 10:00,11:00,12:00', size=10),
        ),
    ]
