# Generated by Django 3.0.3 on 2020-03-02 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
