# Generated by Django 3.0.3 on 2020-03-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='realizadas',
            field=models.BooleanField(default=False),
        ),
    ]
