# Generated by Django 3.0.3 on 2020-03-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_consultation_realizadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='realizadas',
            new_name='realizada',
        ),
    ]
